# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:42
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_score', models.PositiveIntegerField()),
                ('opponent_score', models.PositiveIntegerField()),
                ('your_result', models.PositiveIntegerField(editable=False)),
                ('opponent_result', models.PositiveIntegerField(editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_goals', models.PositiveIntegerField(null=True)),
                ('game', models.ForeignKey(default=blog.models.get_default_game_number, on_delete=django.db.models.deletion.CASCADE, to='blog.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.img_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('bodytext', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('rec_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifa_year', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='fifa_year',
            field=models.ForeignKey(default=blog.models.get_current_year_number, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Year'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Team'),
        ),
        migrations.AddField(
            model_name='goal',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_first_name', to='blog.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season_number',
            field=models.ForeignKey(default=blog.models.get_default_season_number, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='your_first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_first_name', to='blog.Team'),
        ),
    ]
