# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 00:18
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170512_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('player_name',)},
        ),
        migrations.AddField(
            model_name='player',
            name='player_position',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_team_rec_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='profile_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.img_upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='team',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
