# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 21:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_goalagainst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_assists', models.PositiveIntegerField(null=True)),
                ('game', models.ForeignKey(default=blog.models.get_default_game_number, on_delete=django.db.models.deletion.CASCADE, to='blog.Game')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Player')),
            ],
        ),
    ]
