# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_season_special_season_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='author_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
