# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 11:07
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_seasonpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fifa_year',
            field=models.ForeignKey(default=blog.models.get_current_year_number, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Year'),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_year',
            field=models.ForeignKey(default=blog.models.get_current_year_number, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Year'),
        ),
        migrations.AddField(
            model_name='seasonpoint',
            name='fifa_year',
            field=models.ForeignKey(default=blog.models.get_current_year_number, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Year'),
        ),
    ]
