# Generated by Django 2.2.4 on 2019-10-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190817_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tourney_game',
            field=models.BooleanField(default=False),
        ),
    ]
